# Generated by Django 3.1.2 on 2020-10-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(max_length=200, verbose_name='Slug'),
        ),
    ]
