# Generated by Django 3.1.2 on 2020-11-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_post_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, help_text='This will be added as the meta description.', max_length=255),
        ),
    ]
