# Generated by Django 3.1.2 on 2020-11-07 10:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_post_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Category Name')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='Category URL')),
                ('description', models.CharField(max_length=170, validators=[django.core.validators.MinLengthValidator('Description should be at least 10 chars long')], verbose_name='Category description')),
            ],
        ),
    ]
