# Generated by Django 3.1.2 on 2020-11-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='App User', max_length=100, verbose_name='Name'),
        ),
    ]
